import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("Variance:",np.var(arr))
print("Standard Deviation:",np.std(arr))
arr_2d =  np.array([[1,2,3],[4,5,6]])
print("Sum:",np.sum(arr_2d))
print("Sum:",np.sum(arr_2d,axis=0))
print("Sum:",np.sum(arr_2d,axis=1))
print("Sum:",np.sum(arr_2d[arr_2d>3]))